/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hyy_jni_MainActivity */

#ifndef _Included_com_hyy_jni_MainActivity
#define _Included_com_hyy_jni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hyy_jni_MainActivity
 * Method:    getStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hyy_jni_MainActivity_getStringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
